### ISSUE TITLE
micheh/psr7-cache Abandoned

### ISSUE THREAD

**Issue by mav2287** [middlewares/cache#5]
[micheh/psr7-cache](https://github.com/micheh/psr7-cache) is showing as abandoned by composer and shows as read only on GitHub. Ideally a suitable replacement should be found.

**Comment by mikespub** [comment]
You'll find updated packages at [mikespub/middlewares-cache](https://packagist.org/packages/mikespub/middlewares-cache) and [mikespub/micheh-psr7-cache](https://packagist.org/packages/mikespub/micheh-psr7-cache)

And yes, although it wasn't clear from the documentation or tests, this works fine with ETag as well as Last-Modified headers...
I added some ETag tests in https://github.com/mikespub-org/middlewares-cache/commit/204020037fd33459c88c8ec262cfe6734e68bfc9

**Comment by mikespub** [comment]
Updated with PR #6

**Comment by oscarotero** [comment]
released in v3.0.0
